package db

// Flight represents a flight document in MongoDB.
// `bson:"_id,omitempty"` means the _id field is optional and will be generated by MongoDB if not provided.
// Other `bson:"field_name"` tags map struct fields to MongoDB document fields.
type Flight struct {
	FlightNumber   string             `bson:"flight_number"`
    Origin         string             `bson:"origin"`
    Destination    string             `bson:"destination"`
    DepartureTime  string             `bson:"departure_time"`  // Usa string para simplificar pruebas
    ArrivalTime    string             `bson:"arrival_time"`
    Price          float64            `bson:"price"`
    AvailableSeats int                `bson:"available_seats"`
}